doctrine_migrations:
    migrations_paths:
      # List of namespace/path pairs to search for migrations, at least one required
      'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 191
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'

    # Run all migrations in a transaction.
    all_or_nothing: false

    # Adds an extra check in the generated migrations to ensure that is executed on the same database type.
    check_database_platform: true
