# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    input_sync: true    # Synchroniser les textarea (= à tester pour vérifier textes manquants!)
    configs:
        epukarst_config:
          toolbar:
            - { name: 'clipboard', items: [ 'Undo', 'Redo', '-', 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'SelectAll' ] }
            - { name: 'editing', items: [ 'Find', 'Replace' ] }
            - { name: 'document', items: [ 'Source', '-', 'Preview', 'Print', '-', 'Templates' ] }
            - { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] }
            - { name: 'about', items: [ 'About' ] }
            - '/'
            - { name: 'styles', items: [ 'Format', '-', 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', 'Font', 'FontSize', 'TextColor', 'BGColor', '-', 'CopyFormatting', 'RemoveFormat' ] }
            - '/'
            - { name: 'paragraph', items: [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv' ] }
            - { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] }
            - { name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'Iframe' ] }
